name: Release

on:
  push:
    tags:
      - 'v*'  # 推送 v1.9.1 這類標籤時觸發

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build dist/
        run: npm run build

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/law-item-label.user.js
            dist/index.html
            dist/preview/image.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}